import type { City, Activity, Trip, User, AdminStats } from '../types';

export const INITIAL_USER: User = {
  id: 'usr-101',
  name: 'Alex Morgan',
  email: 'alex.morgan@globetrotter.io',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  bio: 'Avid traveler, photographer, and coffee enthusiast exploring one continent at a time.',
  role: 'user',
  preferences: {
    currency: 'USD',
    language: 'English',
    theme: 'dark',
  },
  savedCityIds: ['cty-tokyo', 'cty-paris', 'cty-bali'],
};

export const INITIAL_CITIES: City[] = [
  {
    id: 'cty-tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80',
    description: 'A vibrant metropolis blending futuristic skyscrapers, historic temples, and world-class culinary experiences.',
    costIndex: '$$$',
    popularityScore: 98,
    averageDailyCost: 180,
    tags: ['Culture', 'Food', 'Tech', 'Shopping'],
  },
  {
    id: 'cty-paris',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    description: 'The City of Light boasts romantic boulevards, iconic monuments, world-famous museums, and exquisite cuisine.',
    costIndex: '$$$$',
    popularityScore: 99,
    averageDailyCost: 220,
    tags: ['Romance', 'Art', 'Museums', 'Gastronomy'],
  },
  {
    id: 'cty-rome',
    name: 'Rome',
    country: 'Italy',
    region: 'Europe',
    coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
    description: 'An open-air museum of ancient history, magnificent architecture, delicious pasta, and vibrant street life.',
    costIndex: '$$$',
    popularityScore: 95,
    averageDailyCost: 160,
    tags: ['History', 'Architecture', 'Food', 'Culture'],
  },
  {
    id: 'cty-bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    description: 'Tropical paradise of lush rice terraces, sacred volcanic mountains, serene beaches, and spiritual retreats.',
    costIndex: '$$',
    popularityScore: 94,
    averageDailyCost: 90,
    tags: ['Beach', 'Nature', 'Wellness', 'Adventure'],
  },
  {
    id: 'cty-barcelona',
    name: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    coverImage: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=800&q=80',
    description: 'Sun-drenched Mediterranean coastal city famed for Gaudí architecture, lively tapas bars, and sandy beaches.',
    costIndex: '$$$',
    popularityScore: 92,
    averageDailyCost: 150,
    tags: ['Architecture', 'Beach', 'Nightlife', 'Tapas'],
  },
  {
    id: 'cty-nyc',
    name: 'New York',
    country: 'United States',
    region: 'North America',
    coverImage: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80',
    description: 'The city that never sleeps: Broadway shows, skyline views, diverse neighborhoods, and endless energy.',
    costIndex: '$$$$',
    popularityScore: 97,
    averageDailyCost: 250,
    tags: ['Skyline', 'Broadway', 'Shopping', 'Diverse'],
  },
  {
    id: 'cty-kyoto',
    name: 'Kyoto',
    country: 'Japan',
    region: 'Asia',
    coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    description: 'Japan’s cultural heart filled with classical Buddhist temples, bamboo groves, traditional wooden houses, and geishas.',
    costIndex: '$$$',
    popularityScore: 91,
    averageDailyCost: 140,
    tags: ['Temples', 'Tradition', 'Cherry Blossoms', 'Peaceful'],
  },
  {
    id: 'cty-santorini',
    name: 'Santorini',
    country: 'Greece',
    region: 'Europe',
    coverImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80',
    description: 'Breathtaking Aegean island with whitewashed buildings, blue-domed churches, and famous cliffside sunsets.',
    costIndex: '$$$$',
    popularityScore: 96,
    averageDailyCost: 230,
    tags: ['Island', 'Sunset', 'Luxury', 'Romance'],
  }
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    cityId: 'cty-tokyo',
    cityName: 'Tokyo',
    name: 'Shinjuku Gyoen National Garden & Tea Ceremony',
    category: 'Culture',
    cost: 25,
    durationHours: 2.5,
    rating: 4.9,
    description: 'Walk through serene Japanese landscape gardens and enjoy a traditional matcha tea ceremony.',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    location: 'Shinjuku, Tokyo',
  },
  {
    id: 'act-2',
    cityId: 'cty-tokyo',
    cityName: 'Tokyo',
    name: 'Tsukiji Outer Market Food Tour',
    category: 'Food',
    cost: 65,
    durationHours: 3.0,
    rating: 4.8,
    description: 'Sample fresh sushi, wagyu beef skewers, tamagoyaki, and matcha desserts with a local expert guide.',
    coverImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    location: 'Tsukiji, Tokyo',
  },
  {
    id: 'act-3',
    cityId: 'cty-tokyo',
    cityName: 'Tokyo',
    name: 'teamLab Planets Digital Art Museum',
    category: 'Entertainment',
    cost: 38,
    durationHours: 2.0,
    rating: 4.9,
    description: 'Immerse your senses in body-immersive digital art installations and water mirrors.',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    location: 'Toyosu, Tokyo',
  },
  {
    id: 'act-4',
    cityId: 'cty-tokyo',
    cityName: 'Tokyo',
    name: 'Senso-ji Temple & Asakusa Walking Tour',
    category: 'Sightseeing',
    cost: 15,
    durationHours: 2.0,
    rating: 4.7,
    description: 'Explore Tokyo’s oldest temple, pass under the Thunder Gate, and shop along Nakamise Street.',
    coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80',
    location: 'Asakusa, Tokyo',
  },

  {
    id: 'act-5',
    cityId: 'cty-paris',
    cityName: 'Paris',
    name: 'Eiffel Tower Summit Access & Champagne',
    category: 'Sightseeing',
    cost: 55,
    durationHours: 2.5,
    rating: 4.9,
    description: 'Ascend to the top summit of the Iron Lady for panoramic views of Paris with a glass of bubbly.',
    coverImage: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=800&q=80',
    location: 'Champ de Mars, Paris',
  },
  {
    id: 'act-6',
    cityId: 'cty-paris',
    cityName: 'Paris',
    name: 'Louvre Museum Timed Masterpiece Tour',
    category: 'Culture',
    cost: 45,
    durationHours: 3.0,
    rating: 4.8,
    description: 'Skip-the-line guided access to Mona Lisa, Venus de Milo, and Winged Victory of Samothrace.',
    coverImage: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80',
    location: '1st Arrondissement, Paris',
  },
  {
    id: 'act-7',
    cityId: 'cty-paris',
    cityName: 'Paris',
    name: 'Seine River Evening Dinner Cruise',
    category: 'Food',
    cost: 95,
    durationHours: 2.5,
    rating: 4.8,
    description: 'Enjoy 3-course French dining while floating past illuminated Paris landmarks.',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    location: 'Port de la Bourdonnais, Paris',
  },

  {
    id: 'act-8',
    cityId: 'cty-rome',
    cityName: 'Rome',
    name: 'Colosseum & Roman Forum VIP Access',
    category: 'Sightseeing',
    cost: 50,
    durationHours: 3.0,
    rating: 4.9,
    description: 'Step onto the arena floor where gladiators fought and explore Ancient Rome.',
    coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
    location: 'Piazza del Colosseo, Rome',
  },
  {
    id: 'act-9',
    cityId: 'cty-rome',
    cityName: 'Rome',
    name: 'Trastevere Pasta & Wine Tasting Walk',
    category: 'Food',
    cost: 70,
    durationHours: 3.0,
    rating: 4.9,
    description: 'Taste authentic Cacio e Pepe, Carbonara, gelato, and Chianti in picturesque Trastevere alleys.',
    coverImage: 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&w=800&q=80',
    location: 'Trastevere, Rome',
  },

  {
    id: 'act-10',
    cityId: 'cty-bali',
    cityName: 'Bali',
    name: 'Tegalalang Rice Terrace & Jungle Swing',
    category: 'Adventure',
    cost: 30,
    durationHours: 4.0,
    rating: 4.7,
    description: 'Hike through cascading emerald rice paddies and soar over the canopy on Bali’s famous swing.',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    location: 'Ubud, Bali',
  },
  {
    id: 'act-11',
    cityId: 'cty-bali',
    cityName: 'Bali',
    name: 'Uluwatu Sunset Temple & Kecak Fire Dance',
    category: 'Culture',
    cost: 20,
    durationHours: 3.0,
    rating: 4.8,
    description: 'Watch dramatic cliffside ocean sunset followed by traditional hypnotic Kecak chant dance.',
    coverImage: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=80',
    location: 'Uluwatu, Bali',
  }
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trp-euro-2026',
    userId: 'usr-101',
    name: 'Grand European Escape',
    description: 'A two-week multi-city exploration of Paris romantic art scene and Rome’s ancient monuments.',
    startDate: '2026-09-10',
    endDate: '2026-09-24',
    estimatedBudget: 3500,
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    status: 'upcoming',
    createdAt: '2026-08-01',
    isPublic: true,
    shareToken: 'share-euro-2026-token',
    stops: [
      {
        id: 'stp-1',
        tripId: 'trp-euro-2026',
        cityId: 'cty-paris',
        cityName: 'Paris',
        country: 'France',
        coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
        startDate: '2026-09-10',
        endDate: '2026-09-16',
        orderIndex: 0,
        stayCost: 900,
        transportCost: 350,
        activities: [
          {
            id: 'tact-1',
            stopId: 'stp-1',
            activityId: 'act-5',
            name: 'Eiffel Tower Summit Access & Champagne',
            category: 'Sightseeing',
            startTime: '10:00 AM',
            durationHours: 2.5,
            cost: 55,
            description: 'Ascend to the summit for panoramic views',
            coverImage: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=800&q=80',
            completed: false,
          },
          {
            id: 'tact-2',
            stopId: 'stp-1',
            activityId: 'act-6',
            name: 'Louvre Museum Timed Masterpiece Tour',
            category: 'Culture',
            startTime: '02:00 PM',
            durationHours: 3.0,
            cost: 45,
            description: 'Mona Lisa and classical statues',
            coverImage: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80',
            completed: false,
          },
          {
            id: 'tact-3',
            stopId: 'stp-1',
            activityId: 'act-7',
            name: 'Seine River Evening Dinner Cruise',
            category: 'Food',
            startTime: '07:30 PM',
            durationHours: 2.5,
            cost: 95,
            description: 'French dining on floating boat',
            coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
            completed: false,
          }
        ]
      },
      {
        id: 'stp-2',
        tripId: 'trp-euro-2026',
        cityId: 'cty-rome',
        cityName: 'Rome',
        country: 'Italy',
        coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
        startDate: '2026-09-17',
        endDate: '2026-09-24',
        orderIndex: 1,
        stayCost: 800,
        transportCost: 180,
        activities: [
          {
            id: 'tact-4',
            stopId: 'stp-2',
            activityId: 'act-8',
            name: 'Colosseum & Roman Forum VIP Access',
            category: 'Sightseeing',
            startTime: '09:30 AM',
            durationHours: 3.0,
            cost: 50,
            description: 'Arena floor gladiator view',
            coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
            completed: false,
          },
          {
            id: 'tact-5',
            stopId: 'stp-2',
            activityId: 'act-9',
            name: 'Trastevere Pasta & Wine Tasting Walk',
            category: 'Food',
            startTime: '06:00 PM',
            durationHours: 3.0,
            cost: 70,
            description: 'Traditional Roman dinner tour',
            coverImage: 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&w=800&q=80',
            completed: false,
          }
        ]
      }
    ]
  },
  {
    id: 'trp-japan-spring',
    userId: 'usr-101',
    name: 'Japan Cherry Blossom Odyssey',
    description: 'Immersive dive into Tokyo night culture and Kyoto traditional serenity during spring blossom season.',
    startDate: '2026-04-01',
    endDate: '2026-04-12',
    estimatedBudget: 2800,
    coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80',
    status: 'completed',
    createdAt: '2026-02-10',
    isPublic: true,
    shareToken: 'share-japan-spring-token',
    stops: [
      {
        id: 'stp-3',
        tripId: 'trp-japan-spring',
        cityId: 'cty-tokyo',
        cityName: 'Tokyo',
        country: 'Japan',
        coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80',
        startDate: '2026-04-01',
        endDate: '2026-04-06',
        orderIndex: 0,
        stayCost: 750,
        transportCost: 200,
        activities: [
          {
            id: 'tact-6',
            stopId: 'stp-3',
            activityId: 'act-1',
            name: 'Shinjuku Gyoen National Garden & Tea Ceremony',
            category: 'Culture',
            startTime: '10:00 AM',
            durationHours: 2.5,
            cost: 25,
            description: 'Cherry blossom viewing',
            coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
            completed: true,
          },
          {
            id: 'tact-7',
            stopId: 'stp-3',
            activityId: 'act-3',
            name: 'teamLab Planets Digital Art Museum',
            category: 'Entertainment',
            startTime: '03:00 PM',
            durationHours: 2.0,
            cost: 38,
            description: 'Digital art room',
            coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
            completed: true,
          }
        ]
      }
    ]
  }
];

export const INITIAL_ADMIN_STATS: AdminStats = {
  totalUsers: 14280,
  totalTrips: 38940,
  popularCities: [
    { cityName: 'Tokyo', count: 12450 },
    { cityName: 'Paris', count: 11200 },
    { cityName: 'Rome', count: 8740 },
    { cityName: 'Bali', count: 7650 },
    { cityName: 'Barcelona', count: 6210 },
  ],
  popularCategories: [
    { category: 'Sightseeing', count: 42300 },
    { category: 'Food', count: 35100 },
    { category: 'Culture', count: 24800 },
    { category: 'Adventure', count: 18900 },
    { category: 'Entertainment', count: 14200 },
  ],
  monthlyEngagement: [
    { month: 'Jan', activeUsers: 8400, tripsCreated: 2400 },
    { month: 'Feb', activeUsers: 9100, tripsCreated: 2800 },
    { month: 'Mar', activeUsers: 10500, tripsCreated: 3500 },
    { month: 'Apr', activeUsers: 11800, tripsCreated: 4100 },
    { month: 'May', activeUsers: 13200, tripsCreated: 4800 },
    { month: 'Jun', activeUsers: 15400, tripsCreated: 5900 },
  ]
};
